---
configure_dotfiles: false
configure_osx: false
configure_sudoers: false
configure_terminal: false

configure_dock: true
dockitems_remove:
  - Contacts
  - Facetime
  - Mail
  - Maps
  - Messages
  - Music
  - Photos
  - Podcasts
  - Reminders
  - TV

homebrew_installed_packages:
  - awscli
  - git
  - git-lfs
  - go
  - hub
  - iperf3
  - nmap
  - openssl
  - pyenv
  - pyenv-virtualenv
  - terraform
  - warrensbox/tap/tfswitch
  - wget

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
    - 1password
    - google-cloud-sdk
    - ngrok
    - sublime-text
    - docker
    - google-chrome
    - iterm2
    - parallels
    - postman
    - spectacle
    - visual-studio-code

configure_sublime: false
