---
downloads: ~/.ansible-downloads/

homebrew_taps: []

homebrew_installed_packages:
  - awscli
  - git
  - git-lfs
  - go
  - hub
  - iperf3
  - nmap
  - openssl
  - pyenv
  - pyenv-virtualenv
  - warrensbox/tap/tfswitch
  - wget
  - yamllint

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - google-cloud-sdk
  - ngrok
  - sublime-text
  - docker
  - iterm2
  - postman
  - spectacle
  - visual-studio-code

configure_dotfiles: true
dotfiles_repo: https://github.com/stilljake/dotfiles
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .osx
  - .zshrc

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

configure_dock: true
dockitems_remove:
  - Contacts
  - FaceTime
  - Mail
  - Maps
  - Messages
  - Music
  - Photos
  - Podcasts
  - Reminders
  - TV
  - App Store

dockitems_persist:
  - name: "Google Chrome"
    path: "/Applications/Google Chrome.app/"

  - name: "Sublime Text"
    path: "/Applications/Sublime Text.app/"

  - name: "Terminal"
    path: "/System/Applications/Utilities/Terminal.app/"

  - name: "Slack"
    path: "/Applications/Slack.app/"

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

configure_terminal: true
terminal_profile: "JT-Term"

configure_osx: true
osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

configure_zsh: true

# Set to 'true' to configure Sublime Text.
configure_sublime: false
sublime_base_path: '~/Library/Application Support/Sublime Text'
sublime_config_path: "Packages/User"
sublime_package_control:
  - "DocBlockr"
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "GitHub Flavored Markdown Preview"
  - "Jinja2"
  - "Package Control"
  - "PHP-Twig"
  - "Pretty JSON"
  - "SublimeLinter"
  - "SublimeLinter-contrib-yamllint"
  - "TrailingSpaces"
  - "WordCount"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
